name: wakili
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get_it: ^7.6.0
  injectable: ^2.1.2
  flutter_dotenv: ^5.1.0
  dio: ^5.4.3+1
  shared_preferences: ^2.2.3
  flutter_bloc: ^8.1.4
  equatable: ^2.0.5
  hive: ^2.2.3 
  hive_flutter: ^1.1.0 
  path_provider: ^2.0.11 
  uuid: ^4.3.3 
  dartz: ^0.10.1
  firebase_auth: ^5.3.4
  smooth_page_indicator: ^1.2.1
  cloud_firestore: ^5.5.1
  flutter_animate: ^4.5.2
  firebase_core: ^3.13.0
  firebase_messaging: ^15.1.6
  firebase_storage: ^12.3.7
  auto_route: ^9.2.2
  google_fonts: ^6.2.1
  google_generative_ai: ^0.4.7
  json_annotation: ^4.4.0
  freezed: ^2.4.5
  google_sign_in: ^6.1.6
  intl: ^0.19.0
  shimmer: ^3.0.0
  flutter_staggered_grid_view: ^0.7.0
  cached_network_image: ^3.2.3
  carousel_slider: ^5.0.0
  flutter_localizations:
    sdk: flutter
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.1.7
  json_serializable: ^6.0.1
  injectable_generator: ^2.1.6
  auto_route_generator: ^9.0.0
  mockito: ^5.3.0
  flutter_launcher_icons: ^0.13.1
  font_awesome_flutter: ^10.8.0
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - env/
    - assets/


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/AppIcons (16)/playstore.png"
  min_sdk_android: 21
  remove_alpha_ios: true
