// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzn9CXcqtJ0sanBeV9P4U5iRnyRT0ps0g',
    appId: '1:749843920861:web:64092f22fa5afed4606834',
    messagingSenderId: '749843920861',
    projectId: 'wakili-5400e',
    authDomain: 'wakili-5400e.firebaseapp.com',
    storageBucket: 'wakili-5400e.firebasestorage.app',
    measurementId: 'G-ZCS9W1G2E6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnlyLZgh50MJqbqTSzo8rreQygjkoUIys',
    appId: '1:749843920861:android:12bb646d9696209c606834',
    messagingSenderId: '749843920861',
    projectId: 'wakili-5400e',
    storageBucket: 'wakili-5400e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwWQBr_U88he3pzW_uYWgj1cbUp68kMI8',
    appId: '1:749843920861:ios:4da9889255b3cd00606834',
    messagingSenderId: '749843920861',
    projectId: 'wakili-5400e',
    storageBucket: 'wakili-5400e.firebasestorage.app',
    iosClientId:
        '749843920861-sgfngm0m061e95khlocpcp0ism9udc1q.apps.googleusercontent.com',
    iosBundleId: 'com.example.buenrowakili',
  );
}
