import 'package:hive/hive.dart';
import 'package:uuid/uuid.dart'; // For generating unique IDs
import 'package:wakili/features/wakili/data/models/chat_message.dart';
part 'chat_conversation.g.dart';

@HiveType(typeId: 0) // Unique type ID for this Hive object
class ChatConversation extends HiveObject {
  @HiveField(0)
  final String id;

  @HiveField(1)
  String title; // Title generated by AI

  @HiveField(2)
  final List<ChatMessage> messages;

  @HiveField(3)
  final DateTime timestamp;

  ChatConversation({
    String? id,
    required this.title,
    required this.messages,
    required this.timestamp,
  }) : id = id ?? const Uuid().v4(); // Generate ID if not provided

  ChatConversation copyWith({
    String? id,
    String? title,
    List<ChatMessage>? messages,
    DateTime? timestamp,
  }) {
    return ChatConversation(
      id: id ?? this.id,
      title: title ?? this.title,
      messages: messages ?? this.messages,
      timestamp: timestamp ?? this.timestamp,
    );
  }
}
