name: Deploy static content to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Pages
        uses: actions/configure-pages@v5
        
      - name: Setup flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.27.1'
          cache: true
          cache-key: flutter
          cache-path: ${{ runner.tool_cache }}/flutter

      - name: Install dependencies.
        run: flutter pub get

      # Generate Injectable files 
      - name: Generate DI files
        run: flutter pub run build_runner build --delete-conflicting-outputs
     
      - name: Generate documentation.
        run: dart doc .
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: doc/api
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4